export ZSH="/Users/goncalo/.oh-my-zsh"

ZSH_THEME="spaceship"

plugins=(
  zsh-autosuggestions
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=1'

source $ZSH/oh-my-zsh.sh

alias ls="ls -G -1"
alias dcu="docker compose up"
alias dcd="docker compose down"
alias dcr="docker compose run"

# rbenv

# eval "$(rbenv init -)"
