export ZSH="/Users/goncalo/.oh-my-zsh"

eval "$(rbenv init -)"

ZSH_THEME="robbyrussell-custom"

plugins=(
  git
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

alias ls="ls -G -1"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=1'
